### ISSUE TITLE
Newly generated project unable to start (windows)

### ISSUE THREAD

**Issue by dany-on-demand** [motion/motion#423]
**No** idea what's going on, running as admin solved some errors but not all 🥇  

<details>
<summary> Virus don't click 🤚 </summary>

```Powershell
C:\vmproj                                                                                       
λ motion new badonkadonk && cd badonkadonk && motion                                            
App created successfully! Enjoy                                                                 
To run motion in your new app, do                                                               
  $ cd badonkadonk                                                                              
  $ motion                                                                                      
Server running at http://localhost:12228/                                                       
Type help to get list of available commands                                                     
  Info    Number of files in cache pool: 0                                                      
$root\index.js ✓                                                                                
$root\main.js ✓                                                                                 
Successfully installed react                                                                    
- Installing react-domuncaughtException Error: Error watching file for changes: EPERM           
    at exports._errnoException (util.js:1023:11)                                                
    at FSEvent.FSWatcher._handle.onchange (fs.js:1283:11)                                       
Failed to install react-dom because NPM Error: npm ERR! Windows_NT 10.0.14986                   
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\np
m\\bin\\npm-cli.js" "install" "--save" "react-dom" "--loglevel=error" "--no-color"              
npm ERR! node v7.5.0                                                                            
npm ERR! npm  v4.1.2                                                                            
npm ERR! path C:\vmproj\badonkadonk\node_modules\fbjs                                           
npm ERR! code EPERM                                                                             
npm ERR! errno -4048                                                                            
npm ERR! syscall rename                                                                         
                                                                                                
npm ERR! Error                                                                                  
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.j
s:42:5)                                                                                         
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finaliz
e.js:31:7)                                                                                      
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:2
87:18                                                                                           
npm ERR!     at FSReqWrap.oncomplete (fs.js:112:15)                                             
npm ERR!                                                                                        
npm ERR! Error: EPERM: operation not permitted, rename 'C:\vmproj\badonkadonk\node_modules\fbjs'
 -> 'C:\vmproj\badonkadonk\node_modules\.fbjs.DELETE'                                           
npm ERR!  Error                                                                                 
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.j
s:42:5)                                                                                         
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finaliz
e.js:31:7)                                                                                      
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:2
87:18                                                                                           
npm ERR!     at FSReqWrap.oncomplete (fs.js:112:15)                                             
npm ERR!                                                                                        
npm ERR! Error: EPERM: operation not permitted, rename 'C:\vmproj\badonkadonk\node_modules\fbjs'
 -> 'C:\vmproj\badonkadonk\node_modules\.fbjs.DELETE'                                           
npm ERR!                                                                                        
npm ERR! Please try running this command again as root/Administrator.                           
                                                                                                
npm ERR! Please include the following file with any support request:                            
npm ERR!     C:\vmproj\badonkadonk\npm-debug.log                                                
badonkadonk ❯ Error: Cannot find module 'react-dom/package.json' from 'index.js'                
                                                                                                
badonkadonk ❯                                                                                   
badonkadonk ❯                                                                                   
badonkadonk ❯ exit                                                                              
                                                                                                
```
</details>

**Comment by steelbrain** [comment]
Hi @dany-on-demand 

There's two different things in here

- You are writing to a dir in `C:\` directory, without taking it's ownership first, perms are weird in windows when it comes to C drive so I recommend you do your work in D drive or take ownership of your dir in C
- You are running an oudated version of motion, please upgrade with `npm install -g motion@latest`

**Comment by dany-on-demand** [comment]
It works, I was the folder owner but for some reason the folder is created **read only**

I don't understand, how am I supposed to use pundle with this though? I don't need a react app

**Comment by steelbrain** [comment]
The react part is just the example code, remove the requires for react and you have a Pundle app :D

Also, I've pushed the fixes to pundle-cli and it's stable to use now too! If you want to use it, it's

```
npm install -g pundle@latest
cd /path/somewhere
mkdir my-app
cd my-app
pundle init basic # or "full"
pundle -d # to run dev server
pundle # to generate static output
```

**Comment by dany-on-demand** [comment]
Thanks, still doesn't work though, I tried it back when you pushed the last commit, I still get the same:
<details> <summary>error </summary>

```powershell
λ pundle -d
unhandledRejection Error: Expected Error to be an object, got undefined:undefined
    at Object.<anonymous> (C:\Users\Dany\AppData\Roaming\npm\node_modules\pundle-cli\node_modules\pundle-reporter-default\lib\index.js:44:13)
    at Generator.next (<anonymous>)
    at step (C:\Users\Dany\AppData\Roaming\npm\node_modules\pundle-cli\node_modules\pundle-reporter-default\lib\index.js:21:191)
    at C:\Users\Dany\AppData\Roaming\npm\node_modules\pundle-cli\node_modules\pundle-reporter-default\lib\index.js:21:437
    at Object.<anonymous> (C:\Users\Dany\AppData\Roaming\npm\node_modules\pundle-cli\node_modules\pundle-reporter-default\lib\index.js:21:99)
    at Object.callback (C:\Users\Dany\AppData\Roaming\npm\node_modules\pundle-cli\node_modules\pundle-reporter-default\lib\index.js:72:17)
    at C:\Users\Dany\AppData\Roaming\npm\node_modules\pundle-cli\lib\index.js:251:37
```
</details>

with bash on windows, npm installs pundle but doesn't copy an execution script to global /bin (but for example create-react-app does and it works)

also running lib/index.js doesn't produce any output

**Comment by steelbrain** [comment]
Ahhhh, I am dehydrated, sorry about that, `pundle` vs `pundle-cli`. The latter is the name of the cli package. Also I'm on windows right now, tho I'm setting it up for gaming, I'll give Pundle a kick and report back on my experience

**Comment by dany-on-demand** [comment]
`pundle-cli` worked, thanks! 👍
